FROM microsoft/windowsservercore
RUN mkdir c:\INSTALL
ADD INSTALL c:\INSTALL
WORKDIR C:\\INSTALL
RUN sc config lanmanworkstation depend= "MrxSmb20/NSI"
RUN powershell -Command \
copy-item -Path c:\INSTALL\mapi32.dll -Destination c:\windows\system32\mapi32.dll
RUN vc2008sp1redist_x64.exe /Q
RUN vc2008sp1redist_x86.exe /Q
RUN NDP451-KB2858728-x86-x64-AllOS-ENU.exe /q /norestart 
RUN c:\windows\system32\msiexec.exe /i python-2.7.9.amd64.msi /qn ALLUSERS=1 MSIFASTINSTALL=7 REBOOT=ReallySuppress CLIENTUILEVEL=3 MSICLIENTUSESEXTERNALUI=1 CLIENTPROCESSID=1020
RUN c:\INSTALL\vc_2005_sp1_redist_x64.exe /Q
RUN c:\INSTALL\vc_2013_redist_x64.exe /quiet /norestart
RUN c:\windows\system32\msiexec.exe /i Redis-x64-3.0.500.msi /qn
RUN powershell.exe -Command \
start-process jre-8u101-windows-x64.exe -ArgumentList '/s REPAIRMODE=1 WEB_JAVA=0' -wait